### ISSUE TITLE
dev-java/jdom-1.1.3-r1 fails to compile: environment: line 1304: xml-rewrite-3.py: No such file or directory 

### ISSUE THREAD

**Issue by asarubbo** [2Kmm/java#15] opened 2024-06-03 06:46 UTC
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-java/jdom-1.1.3-r1 fails to compile.
Discovered on: amd64 (internal ref: java-test_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0014

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/90c38e128dcf6636fb1a047b2ed5f807

**Comment by vaukai** [comment] 2024-06-03 10:20
@fordfrog
i am almost sure this is a regression of https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=d19b5533e56067a6058b7e77497e93efb011b834 or https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5c70bf44a9aa9973e6e08941c9b0bcdb7c8d4560 
not sure if https://github.com/gentoo/gentoo/pull/36984 could solve it.
i suggest solving this bug with 4th commit of https://github.com/gentoo/gentoo/pull/36770

maybe a good reason to have the xml scrambler phased out asap? and rewrite what's really needed with `xslt`?

**Comment by 2Kmm** [comment] 2024-06-03 10:51
Seems unrelated to changes in `java-pkg-simple.eclass` - closing

**Closed by 2Kmm** 2024-06-03 10:51 UTC

**Comment by fordfrog** [comment] 2024-06-04 09:04
> @fordfrog i am almost sure this is a regression of https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=d19b5533e56067a6058b7e77497e93efb011b834 or https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5c70bf44a9aa9973e6e08941c9b0bcdb7c8d4560 not sure if [gentoo/gentoo#36984](https://github.com/gentoo/gentoo/pull/36984) could solve it. i suggest solving this bug with 4th commit of [gentoo/gentoo#36770](https://github.com/gentoo/gentoo/pull/36770)
> 
> maybe a good reason to have the xml scrambler phased out asap? and rewrite what's really needed with `xslt`?

well, this was introduced by my javatoolkit commit. anyway, i don't really like that build.xml rewriting which is needed for ant build systems, but with your effort of moving package to java-pkg-simple at least the usage has been greatly reduced. but i'm not sure we could get rid of it completely, which i'd wish we could.

**Comment by vaukai** [comment] 2024-06-04 13:40
> i don't really like that build.xml rewriting which is needed for ant build systems, but with your effort of moving package to java-pkg-simple at least the usage has been greatly reduced. but i'm not sure we could get rid of it completely, which i'd wish we could.

we can. from the [present state](https://qa-reports.gentoo.org/output/eapi-per-eclass/java-ant-2.eclass/), EAPI=7 is practically done (presently fighting with `hsqldb`). 
the ugly part is `eant` forcing `java-ant-2_src_configure()` 
```
java-ant-2_src_configure() {
	# if java support is optional, don't perform this when the USE flag is off
	if has java-pkg-opt-2 ${INHERITED}; then
		use ${JAVA_PKG_OPT_USE} || return
	fi

	# eant will call us unless called by Portage
	[[ -e "${T}/java-ant-2_src_configure-run" ]] && return

	[[ "${JAVA_ANT_IGNORE_SYSTEM_CLASSES}" ]] \
		&& java-ant_ignore-system-classes "${S}/build.xml"

	java-ant_bsfix
	touch "${T}/java-ant-2_src_configure-run"
}
```
which was the reason for me putting `java-ant-2_src_configure-run` in the [lucene ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-java/lucene/lucene-2.4.1-r4.ebuild).
the eant() function, if we want to keep using it, should get a condition to force inheriting `java-ant-2.eclass` only and really only when the ebuild has real need for scrambing the `build.xml`.

even without such an enhancement to `eant()`, we could proceed trying `java-ant-2_src_configure-run` in the remaining ebuilds.
wrt `tomcat`, the only question is: what is EANT_BUILD_TARGET="deploy"? (i could not find a `deploy` target in `build.xml`)
